services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-jodev
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`jodev.my.id`) || Host(`www.jodev.my.id`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - madena_network

networks:
  madena_network:
    external: true
    name: my-madena_madena_network
